### ISSUE TITLE
Not creating Session Can you help to integrate klarna payment. is there any working example.

### ISSUE THREAD

**Issue by dev-dubaisoftwaresolutions** [klarna/kp-ios-example-app#1]
FashionStore-CocoaPods[9347:135672] CredStore - performQuery - Error copying matching creds.  Error=-25300, query={
    class = inet;
    "m_Limit" = "m_LimitAll";
    ptcl = htps;
    "r_Attributes" = 1;
    sdmn = "very closed site";
    srvr = "api.playground.klarna.com";
    sync = syna;
}
BackendOperations createDataTask: The data couldn’t be read because it isn’t in the correct format.

**Comment by omarbh** [comment]
Hi,
Thanks for reporting this 👍 . What's the merchant id of your playground store? 
We will create a ticket in our backlog and we will investigate this soon.
Cheers

**Comment by omarbh** [comment]
Closing this as the user could not provide more information
