### ISSUE TITLE
Does'nt work with XCode 11.2

### ISSUE THREAD

**Issue by matsjansson** [klarna/kp-ios-example-app#4]
The framwork is compiled with an older version ant you get the: Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1.2 compiler: /Users/maja/Develop/xx/Pods/KlarnaMobileSDK/ios/xcode103-swift5-fat/KlarnaMobileSDK.framework/Modules/KlarnaMobileSDK.swiftmodule/x86_64.swiftmodule

**Comment by omarbh** [comment]
Hi, 
the latest version should support the latest Swift version, please double check an reopen the issue if needed.
Cheers
