### ISSUE TITLE
Change Podfile to use Cocoapods CDN

### ISSUE THREAD

**Issue by richellis** [klarna/kp-ios-example-app#6]
**Describe the bug**
`pod install` for this sample project takes forever because it is using the old-style git source instead of the CDN.

**To Reproduce**
1. Clone this project's repo
2. `pod install --repo-update` per the instructions
3. Wait a *really* long time for the Cocoapods Specs repo to be cloned

**Expected behavior**
Use the Cocoapods CDN and the `pod install` is nearly instantaneous. Change your `Podfile`'s `source`:
```
source "https://cdn.cocoapods.org/"
```

**Comment by omarbh** [comment]
Thanks @richellis, we will fix this.

**Comment by polar133** [comment]
Thanks @richellis, it was updated.
